# Generated by Django 2.1.1 on 2018-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='世界知名', max_length=10, verbose_name='机构标签'),
        ),
    ]
